FROM python:3.8

# os environment setting
WORKDIR /usr/src/app
RUN apt-get update
RUN apt-get -y install libgl1-mesa-glx default-libmysqlclient-dev build-essential pkg-config;

# skip the original code
COPY ./requirements.txt .

#
RUN pip install --no-cache-dir --upgrade -r requirements.txt

#
CMD ["uvicorn", "app:fastapi_app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
